version: '2'
services:
  masternode:
    build: ./masternode
    command: npm run start
    volumes:
      - ./masternode/:/usr/app/
      - /usr/app/node_modules
    ports:
      - "5000:5000"
      - "8080:8080"
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/public
    volumes_from:
      - masternode
    links:
      - masternode:masternode
