# Sample Configuration File

[server]
ip = "0.0.0.0"
port = 80
threads = 4
idle_timeout_ms = 20000
    [server.cache]
    max_entries = 1024
    disk_path = "/home/me/cache"

# Protected domains
[[protected-domain]]
domain_name = "blog.gladius.io"
origin_server_host = "127.0.0.1"
origin_server_port = 80

[[protected-domain]]
domain_name = "mail.gladius.io"
origin_server_host = "127.0.0.2"
origin_server_port = 8080

####################

[features]
    [features.peer-to-peer-cdn]
    enabled = true
    gladius_gateway_address = "127.0.0.1"
    gladius_gateway_port = 3001
    pool_domain = "gladiuspool.com"
    cdn_subdomain = "cdn1"
    poll_interval = 5
    ignore_heartbeat = false

    [features.service-worker-injection]
    enabled = true
    path = "/home/me/service-worker.js"

    [features.compression]
    enabled = true
    level = 5
    minimum_size = 1024

# SSL Settings
[ssl]
enabled = true
upgrade_insecure = true
port = 443
    [[ssl.certificate]]
    cert_path = "/home/me/cert.pem"
    key_path = "/home/me/key.pem"
    is_default = true

    [[ssl.certificate]]
    cert_path = "/home/me/cert2.pem"
    key_path = "/home/me/key2.pem"
